/**
 * Copyright (c) 2017, curiator.com, All rights reserved.
 * JavaScript ver. 2.5
 */ 

function LimitBrowsing(){this.limit=15;this.pagesViewed=Cookies.get("pages-viewed")?Cookies.get("pages-viewed"):0;this.pagesToCount=["welcome","art","user","curatorials","search"];this.maybeLimit()}
LimitBrowsing.prototype.maybeLimit=function(){if(parseInt(Cookies.get("is_member")))return false;if(this.pagesToCount.indexOf(getPage())!=-1){if(!this.pagesViewed)setTimeout(function(){if(!$("#shadow-box").length)showDialogAbout()},3E3);this.pagesViewed++;if(this.pagesViewed>this.limit){showDialogSignUp();this.reset()}storeCookie("pages-viewed",this.pagesViewed,0)}};LimitBrowsing.prototype.reset=function(){if(crtrIsMobileSite())this.pagesViewed=-50;else this.pagesViewed=0};$(document).ready(function(){if(!isLoggedIn());initLoggedoutNav();if(typeof LimitBrowsing=="function")sg("limitbrowsing",new LimitBrowsing);$(".members-only").click(function(){var action=$(this).attr("data-action");if(!action)action="go here";showDialogLoginRequired(action,$(this));return false});$("#join-now").click(joinNow);handleLoginError();maybeDoAutoLogin()});
function initLoggedoutNav(){$("#main-nav-loggedout .btn-about").click(showDialogAbout);$("#main-nav-loggedout .btn-sign-in").click(showDialogLogin);$("#main-nav-loggedout .btn-sign-up").click(function(){window.location.href="/signup"})}
function handleLoginError(){var index=window.location.href.indexOf("#");if(index>-1)if(window.location.href.indexOf("failure")!=-1){var code=window.location.href.substr(index+1,10);if(code=="g:404")s("Dialog").show("welcome_upgrade_gplus",null,null,function(){$("#dialog .google-login, #dialog .facebook-login, #dialog .tumblr-login").click(performLogin)});else if(code=="connect")s("Dialog").error('We were unable to connect your social media account.</p><p>If you keep on having trouble logging in, please contact <a href="#" class="render-email incog" data-alias="support"></a>');
else if(code=="account")s("Dialog").display("Account not registered","Please create an account before logging in.",{"cancel":true,"submit":"create account"},joinNow);else if(code=="email")s("Dialog").display("Permission error",'We were unable to get your email from your social media account.</p><p>If you keep on having trouble logging in, please contact <a href="#" class="render-email incog" data-alias="support"></a>.');storeLoginType("");window.history.pushState(null,null,window.location.href.substr(0,
index))}}function maybeDoAutoLogin(){if(getURLParameter("logout")!==null){storeLoginType("");return}if(getURLParameter("from_app"))return;var loginType=Cookies.get("login_type");storeLoginType("");if(loginType=="facebook"||loginType=="google")s("Dialog").show("global_auto_login",{"login_type":loginType},null,$.proxy(doAutoLogin,this,loginType));else if(loginType=="regular")showDialogLogin()}
function collapseNavLoginForm(){$("#login-buttons .login-oldschool").css({"width":120,"background-position":"-70px 0"});$("#login-buttons .login-oldschool-form-wrapper").width(0);$("#login-buttons .ip-email").removeClass("error").val("").blur();$("#login-buttons .ip-password").removeClass("error").val("").blur();$("#login-buttons .login-instructions").show()}
function doAutoLogin(loginType){$.ajax({"url":"/a/_glu","type":"post","dataType":"json","data":{"type":loginType,"autologin":1}}).done(function(data){$("#login-iframe").load(function(){try{if($("#login-iframe").contents())top.location.reload()}catch(e){setTimeout(function(){$("#login-now").click(function(){performLogin(null,loginType)});s("Dialog").nextStep()},400)}}).attr("src",data.url)})}
function performLogin(e,type){if(!type)if($(this).hasClass("facebook"))type="facebook";else if($(this).hasClass("google"))type="google";else if($(this).hasClass("tumblr"))type="tumblr";if(e&&$(this).hasClass("btn-platform")){$(".btn-platform").removeClass("anim-wait");$(this).addClass("anim-wait")}$.ajax({"url":"/a/_glu"+($("#signup-buttons").length?"/signup":""),"type":"post","dataType":"json","data":{"type":type}}).done(function(data){storeLoginType(type);window.onbeforeunload=null;top.location.href=
data.url})};
